scripts: rewrite grimshot

diff --git a/bin/grimshot b/bin/grimshot
--- a/bin/grimshot
+++ b/bin/grimshot
@@ -1,168 +1,78 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
-## Grimshot: a helper for screenshots within sway
-## Requirements:
-##  - `grim`: screenshot utility for wayland
-##  - `slurp`: to select an area
-##  - `swaymsg`: to read properties of current window
-##  - `wl-copy`: clipboard utility
-##  - `jq`: json utility to parse swaymsg output
-##  - `notify-send`: to show notifications
-## Those are needed to be installed, if unsure, run `grimshot check`
-##
-## See `man 1 grimshot` or `grimshot usage` for further details.
+# Screenshot
+#
+# Saves file in $GRIM_DEFAULT_DIR, falling back to $XDG_PICTURES_DIR and
+# finally to $HOME directory.
+#
+# Use "grimshot screen" to take a picture of the whole screen.
+# Use "grimshot area" to take a picture of an area.
+#
+# Add a '--copy' flag after the action to copy to clipboard instead of saving
+# to file.
+#
+# A notification would be sent with a small preview of the screenshot after a
+# successful run.
+#
+# Requires
+# 	grim
+# 	slurp
+# 	notify-send
+# 	date
+# 	wl-copy (for --copy)
 
-getTargetDirectory() {
-  test -f "${XDG_CONFIG_HOME:-$HOME/.config}/user-dirs.dirs" && \
-    . "${XDG_CONFIG_HOME:-$HOME/.config}/user-dirs.dirs"
-
-  echo "${XDG_SCREENSHOTS_DIR:-${XDG_PICTURES_DIR:-$HOME}}"
+# Arguments:
+# 	FILE: filename to save the file to
+# 	GEOMETRY(optional): area to take a screenshot of
+screenshot() {
+	if [ -z "$2" ]; then
+		grim "$1" || die "Unable to call grim!"
+	else
+		grim -g "$2" "$1" || die "Unable to call grim!"
+	fi
 }
 
-NOTIFY=no
-CURSOR=
-
-while [ $# -gt 0 ]; do
-  key="$1"
-
-  case $key in
-    -n|--notify)
-      NOTIFY=yes
-      shift # past argument
-      ;;
-    -c|--cursor)
-      CURSOR=yes
-      shift # past argument
-      ;;
-    *)    # unknown option
-      break # done with parsing --flags
-      ;;
-  esac
-done
-
-ACTION=${1:-usage}
-SUBJECT=${2:-screen}
-FILE=${3:-$(getTargetDirectory)/$(date -Ins).png}
-
-if [ "$ACTION" != "save" ] && [ "$ACTION" != "copy" ] && [ "$ACTION" != "check" ]; then
-  echo "Usage:"
-  echo "  grimshot [--notify] [--cursor] (copy|save) [active|screen|output|area|window] [FILE|-]"
-  echo "  grimshot check"
-  echo "  grimshot usage"
-  echo ""
-  echo "Commands:"
-  echo "  copy: Copy the screenshot data into the clipboard."
-  echo "  save: Save the screenshot to a regular file or '-' to pipe to STDOUT."
-  echo "  check: Verify if required tools are installed and exit."
-  echo "  usage: Show this message and exit."
-  echo ""
-  echo "Targets:"
-  echo "  active: Currently active window."
-  echo "  screen: All visible outputs."
-  echo "  output: Currently active output."
-  echo "  area: Manually select a region."
-  echo "  window: Manually select a window."
-  exit
-fi
-
-notify() {
-  notify-send -t 3000 -a grimshot "$@"
-}
-notifyOk() {
-  [ "$NOTIFY" = "no" ] && return
-
-  TITLE=${2:-"Screenshot"}
-  MESSAGE=${1:-"OK"}
-  notify "$TITLE" "$MESSAGE"
-}
-notifyError() {
-  if [ $NOTIFY = "yes" ]; then
-    TITLE=${2:-"Screenshot"}
-    MESSAGE=${1:-"Error taking screenshot with grim"}
-    notify -u critical "$TITLE" "$MESSAGE"
-  else
-    echo "$1"
-  fi
-}
-
+# Arguments:
+# 	MSG: the error message to show to the user
 die() {
-  MSG=${1:-Bye}
-  notifyError "Error: $MSG"
-  exit 2
+	MSG=${1:-No error message was given}
+	notify-send -u critical "Unable to take a Screenshot!" "$MSG"
+	exit 2
 }
 
-check() {
-  COMMAND=$1
-  if command -v "$COMMAND" > /dev/null 2>&1; then
-    RESULT="OK"
-  else
-    RESULT="NOT FOUND"
-  fi
-  echo "   $COMMAND: $RESULT"
-}
+DIR=${GRIM_DEFAULT_DIR:-$XDG_PICTURES_DIR}
+DIR=${DIR:-$HOME}
 
-takeScreenshot() {
-  FILE=$1
-  GEOM=$2
-  OUTPUT=$3
-  if [ -n "$OUTPUT" ]; then
-    grim ${CURSOR:+-c} -o "$OUTPUT" "$FILE" || die "Unable to invoke grim"
-  elif [ -z "$GEOM" ]; then
-    grim ${CURSOR:+-c} "$FILE" || die "Unable to invoke grim"
-  else
-    grim ${CURSOR:+-c} -g "$GEOM" "$FILE" || die "Unable to invoke grim"
-  fi
-}
+SCREEN="screen";
+AREA="area";
 
-if [ "$ACTION" = "check" ] ; then
-  echo "Checking if required tools are installed. If something is missing, install it to your system and make it available in PATH..."
-  check grim
-  check slurp
-  check swaymsg
-  check wl-copy
-  check jq
-  check notify-send
-  exit
-elif [ "$SUBJECT" = "area" ] ; then
-  GEOM=$(slurp -d)
-  # Check if user exited slurp without selecting the area
-  if [ -z "$GEOM" ]; then
-    exit 1
-  fi
-  WHAT="Area"
-elif [ "$SUBJECT" = "active" ] ; then
-  FOCUSED=$(swaymsg -t get_tree | jq -r 'recurse(.nodes[]?, .floating_nodes[]?) | select(.focused)')
-  GEOM=$(echo "$FOCUSED" | jq -r '.rect | "\(.x),\(.y) \(.width)x\(.height)"')
-  APP_ID=$(echo "$FOCUSED" | jq -r '.app_id')
-  WHAT="$APP_ID window"
-elif [ "$SUBJECT" = "screen" ] ; then
-  GEOM=""
-  WHAT="Screen"
-elif [ "$SUBJECT" = "output" ] ; then
-  GEOM=""
-  OUTPUT=$(swaymsg -t get_outputs | jq -r '.[] | select(.focused)' | jq -r '.name')
-  WHAT="$OUTPUT"
-elif [ "$SUBJECT" = "window" ] ; then
-  GEOM=$(swaymsg -t get_tree | jq -r '.. | select(.pid? and .visible?) | .rect | "\(.x),\(.y) \(.width)x\(.height)"' | slurp)
-  # Check if user exited slurp without selecting the area
-  if [ -z "$GEOM" ]; then
-   exit 1
-  fi
-  WHAT="Window"
-else
-  die "Unknown subject to take a screen shot from" "$SUBJECT"
+ACTION=$1
+COPY=$2
+
+FILE="${DIR}/$(date +"%F_%T.png")"
+GEOM=""
+
+if [ $# -gt 2 ]; then
+	die "Too many arguments!"
 fi
 
-if [ "$ACTION" = "copy" ] ; then
-  takeScreenshot - "$GEOM" "$OUTPUT" | wl-copy --type image/png || die "Clipboard error"
-  notifyOk "$WHAT copied to buffer"
+case $ACTION in
+	$SCREEN)
+		GEOM=""
+		;;
+	$AREA)
+		GEOM="$(slurp)"
+		;;
+	*)
+		die "Please specify either 'screen' or 'area' for the action!"
+		;;
+esac
+
+if [ "$COPY" = "--copy" ]; then
+	FILE="-"
+	screenshot "$FILE" "$GEOM" | wl-copy || die "Unable to copy the screenshot to clipboard!"
+	notify-send "Screenshot Taken!" "Saved to clipboard."
 else
-  if takeScreenshot "$FILE" "$GEOM" "$OUTPUT"; then
-    TITLE="Screenshot of $SUBJECT"
-    MESSAGE=$(basename "$FILE")
-    notifyOk "$MESSAGE" "$TITLE"
-    echo "$FILE"
-  else
-    notifyError "Error taking screenshot with grim"
-  fi
+	screenshot "$FILE" "$GEOM"
+	notify-send "Screenshot Taken!" "Saved in ${DIR} as \"${FILE##*/}\"." -i ${FILE}
 fi
